# This is a basic workflow to help you get started with Actions

name: Fetch Articles

on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 0 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          npm install -g medium-to-markdown@latest

      - name: Fetch articles
        run: |
          topic="prompt-engineering"
          medium-to-markdown --limit 10 --tag "${topic}" --output links.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Add links to ${topic} articles"
          title: "Add links to ${topic} articles"
          body: |
            This pull request adds links to articles on the topic "${topic}" from Medium.

            Please review and merge if appropriate.
          branch: "add-links-${topic}"
          base: main
          path: "links.md"
