# This is a basic workflow to help you get started with Actions

name: Fetch Articles

on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 0 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch articles
        env:
          GITHUB_TOKEN: ${{ secrets.AWESOME }}
        run: |
          topic="prompt-engineering"
          articles=$(curl -s "https://medium.com/search?q=${topic}" \
            | cheerio 'a.postArticle-content[href]' \
            | attr href \
            | sort \
            | uniq)

          for article in ${articles}; do
            echo "- [$(curl -s ${article} | cheerio 'h1' | text)](${article})" >> links.md
          done

