# This is a basic workflow to help you get started with Actions

name: Fetch Articles

on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 0 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch articles
        env:
          GITHUB_TOKEN: ${{ secrets.AWESOME }}
        run: |
          topic="prompt-engineering"
          articles=$(curl -s "https://medium.com/search?q=${topic}" \
            | grep -Eo 'href="https://medium.com/[^"]+"' \
            | sed -E 's/^href="//;s/"$//' \
            | sort \
            | uniq)

          echo "# ${topic} Articles" > links.md
          for article in ${articles}; do
            title=$(curl -s ${article} | grep -o '<title>.*</title>' | sed -E 's/<title>(.*)<\/title>/\1/')
            echo "- [${title}](${article})" >> links.md
          done

      - name: Commit changes
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.AWESOME }}
        with:
          method: PUT
          url: https://api.github.com/repos/${{ github.repository }}/contents/links.md
          headers: |
            {
              "Content-Type": "application/json",
              "Accept": "application/vnd.github+json"
            }
          body: |
            {
              "message": "Add links to ${topic} articles",
              "content": "$(base64 links.md)",
              "sha": "$(curl -s https://api.github.com/repos/${{ github.repository }}/contents/links.md | jq -r '.sha')",
              "branch": "${{ github.ref }}"
            }
