# This is a basic workflow to help you get started with Actions

name: Fetch Articles

on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 0 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          npm install -g jsdom

      - name: Fetch articles
        run: |
          topic="prompt-engineering"
          jsdom -e 'console.log([...document.querySelectorAll(".postArticle > div > div > div > h3 > a")].map((link) => `* [${link.textContent}](${link.href})`).join("\n"))' https://towardsdatascience.com/tagged/${topic} > links.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Add links to TDS articles on ${topic}"
          title: "Add links to TDS articles on ${topic}"
          body: |
            This pull request adds links to articles on the topic "${topic}" from Towards Data Science.

            Please review and merge if appropriate.
          branch: "add-links-tds-${topic}"
          base: main
          path: "links.md"

