# This is a basic workflow to help you get started with Actions

name: Fetch Articles

on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 0 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          npm install -g medium-to-markdown@latest

      - name: Fetch articles
        run: |
          topic="prompt-engineering"
          medium-to-markdown --limit 10 --tag "${topic}" --output links.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add links to ${topic} articles"
          commit_options: "--author 'GitHub Action <action@github.com>'"
          branch: main
          file_pattern: links.md
