# This is a basic workflow to help you get started with Actions

name: Fetch Articles

on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 0 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          npm install -g puppeteer

      - name: Fetch articles
        run: |
          topic="your-topic-here"
          echo "* [Medium articles on ${topic}](https://medium.com/topic/${topic})" > README.md
          node - << EOF
          const puppeteer = require('puppeteer');
          (async () => {
              const browser = await puppeteer.launch({ headless: true });
              const page = await browser.newPage();
              await page.goto(\`https://medium.com/topic/${topic}\`);
              const links = await page.$$eval('a[href^="/"]', (links) => links.map((link) => {
                  if (link.getAttribute('href').startsWith('/p/')) {
                      return \`* [\${link.textContent}](https://medium.com\${link.getAttribute('href')})\`;
                  }
              }).filter(Boolean).join('\n'));
              await browser.close();
              const readme = await fs.promises.readFile('README.md', 'utf-8');
              const newReadme = readme + '\n\n' + links;
              await fs.promises.writeFile('README.md', newReadme);
          })();
          EOF

      - name: Configure Git
        run: |
          git config --global user.name "aryashah2k"
          git config --global user.email "arya.shah82@nmims.edu.in"

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          add: "."
          message: "Update links to Medium articles on ${topic}"
          push: true
          default_author: true
