# This is a basic workflow to help you get started with Actions

name: Fetch Articles

on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 0 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          npm install -g jsdom

      - name: Fetch articles
        run: |
          topic="prompt-engineering"
          jsdom -e 'console.log([...document.querySelectorAll("a[href^=\"/topic/${topic}\"]:not([class]):not([aria-label]):not([aria-labelledby]):not([aria-hidden]):not([role])")].map((link) => `* [${link.textContent}](${link.href})`).join("\n"))' https://medium.com/topic/${topic} > README.md

      - name: Configure Git
        run: |
          git config --global user.name "aryashah2k"
          git config --global user.email "arya.shah82@nmims.edu.in"

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          add: "."
          message: "Update links to Medium articles on ${topic}"
          push: true
          default_author: true
